### ISSUE TITLE
Missing assembly references

### ISSUE THREAD

**Issue by Southgrove** [dotBunny/VSCode#9] opened 2015-09-11 08:37 UTC
Hi! I'm getting a lot of ...

"[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The type or namespace name `SomeClass' could not be found. Are you missing an assembly reference?"

Did I do something stupid or are the project files not properly set up for VSCode?

Edit: These are third party assemblies btw.

**Comment by B2D235** [comment] 2015-09-11 10:39
I'm also getting this, loads of them. Not too sure what I did but I got one error and a bunch of warnings. The error was also regarding OmniSharp and DNVM/DNX stuff missing, so I followed the link and I have fixed that (I hope) - but all these warnings are present and it seems everything relating to Unity C# is missing (Vector3, StartCoroutine, etc).

**Comment by Southgrove** [comment] 2015-09-11 13:13
IntelliSense is working fine for me. I only have problems with 3rd party referensed libraries (DLLs).

**Comment by reapazor** [comment] 2015-09-11 13:23
I'll setup a test with third party libraries tonight and get back to you on this :)

**Comment by Southgrove** [comment] 2015-09-11 13:26
![Yaaaay](http://cdn.militaryspouse.com/wp-content/uploads/2015/07/8.gif)

**Comment by B2D235** [comment] 2015-09-11 13:36
Sorry if I'm supposed to make a new issue for this (New to a lot of this stuff) and I'm not sure if mine is similar to what Southgrove experianced.

Here is a screenshot of the OmniSharp Log
![image](https://cloud.githubusercontent.com/assets/14233348/9815973/e2f56794-5891-11e5-8b61-6d49f56a9132.png)

and from editor
![image](https://cloud.githubusercontent.com/assets/14233348/9816051/578859cc-5892-11e5-9356-195b551a60ef.png)

**Comment by B2D235** [comment] 2015-09-11 15:08
Hmm, ok so I've got a work around so it works for me, but it looks like I have to do it each time.

I open Unity, and turn off "Enable Integration", I tried turning it back on then opening a script, still nothing - It's only when I try to open a script with integration turned off (It'll open, but no side bar or anything working) and I close it again, and THEN turn back on enable integration, that the scripts will will work properly and I get no warnings of projects not loading.

The moment I close it all, then open Unity again, and double click a script - I am presented with the a screen like above, and have to do the steps all over again to get going.

Some other things I've noticed through this - If I close Unity, after getting Code to work with full integration, and then relaunch Code, everything will still work. But the very moment I open Unity again and go into my Project, it's back to square one.

**Comment by reapazor** [comment] 2015-09-11 19:29
This is looking like an issue with Mono not being installed outside of the Unity install.
I think I have a fix for that specifically where I'll hint back to the Unity libraries instead. 

I'll try to get to this this weekend, etc.

**Comment by reapazor** [comment] 2015-09-12 04:18
I was able to load a CLR 2 DLL into Unity, and am able to see its classes/etc inside of my test project in Visual Studio Code. :(

**Comment by Southgrove** [comment] 2015-09-12 07:15
Hmm. I've got a bunch of conditional compiling going on. Could that be it perhaps?

**Comment by reapazor** [comment] 2015-09-12 13:21
I'm not sure that should break everything as far as you've described. The problem for me is that I can't really fully debug the Visual Studio Code side as far/much as I would like.

They don't seem to support conditionals in the code itself, or atleast in showing blocks that are not going to be compiled). However, I would assume that OmniSharp supports the conditionals out of the box.

Can you create a small reproduction project and zip it up for me? send it to reapazor 'at' gmail 'dot' com and I'll double check everything on my end against it exactly.

I also think I ruled out the mono issue, but I updated the README to always suggest installing the latest mono just incase :)

**Comment by Southgrove** [comment] 2015-09-12 13:34
Alright. I'll set up an example project in a couple of hours. :)

**Comment by Southgrove** [comment] 2015-09-13 00:02
Forgot about the project stuff and ended up playing Metal Gear Solid V all night. :)

Will fix test project tomorrow!

**Comment by Southgrove** [comment] 2015-09-14 07:43
I didn't die. I'm just having some problems recreating the issue, hehe.

**Comment by reapazor** [comment] 2015-09-14 22:08
Well if you want, im not gonna object. 
I understand if you cant though :)

**Comment by Southgrove** [comment] 2015-09-15 05:27
I'll give it another go today with another plugin.

**Comment by Southgrove** [comment] 2015-09-16 11:44
Hey! Sent you an email with a project that fails. =)

**Comment by DDReaper** [comment] 2015-09-17 15:55
I might suggest one other thing.  I had a similar issue during the 0.8 beta.
Tye uninstalling VSCode and installing it fresh, the upgrade may have missed something in the OmniSharp update.

**Comment by Souk21** [comment] 2015-10-11 18:17
Hi! Same issue here:

[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The type or namespace name `SomeClass' could not be found. Are you missing an assembly reference?

I just have mad a fresh install of VSCode.
I'm running OSX 10.9.5, VSCode 0.8.0, Unity 5.2.1f1, mono is up to date, DNX too.

I tried with an empty project and get this log:

[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Skipped unsupported project type 'Assembly-CSharp.csproj'

And then it says "Select Project" and there's no project.

thanks for your plugin :)

**Comment by reapazor** [comment] 2015-10-17 20:52
Hey folks ... if you would be so kind as to try the latest (2.2) and see if that fixes your problem. I was able to reproduce this problem reliably this weekend and come up with a solution (i think).

**Closed** 2015-10-17 20:53 UTC

**Comment by DDReaper** [comment] 2015-10-19 12:23
Ok, initial tests were positive and it seems to be working fine with the new "preferences" VSCode option.
Definitely hiding .meta files but not .sln / .csproj, is this expected? (basically root folder files)

**Comment by reapazor** [comment] 2015-10-19 13:16
Right now i have it leaving the solution / project files still visible ... I'm asking for verification from the @code team on that. I had some issues when I hid them myself.

What do you mean by sync loss? @code guys said it was fine to link to the CMD :)


Ya I gotta update that PDF for next release.
