### ISSUE TITLE
Can't Start OmniSharp

### ISSUE THREAD

**Issue by vexir** [dotBunny/VSCode#2] opened 2015-09-02 18:42 UTC
Looks like OmniSharp can't start, so many features aren't working? My log:
```
[INFO] Starting OmniSharp at '/Users/mathe015/Repositories/MatchThreeMoji/MatchThreeMoji-csharp.sln'...
[INFO] Started OmniSharp from '/Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/omnisharp' with process id 77938...
Can't find custom attr constructor image: /Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/approot/packages/Microsoft.AspNet.Cryptography.Internal/1.0.0-beta4/lib/dnx451/Microsoft.AspNet.Cryptography.Internal.dll mtoken: 0x0a000004
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
Stacktrace:

  at <unknown> <0xffffffff>
  at Microsoft.Framework.DependencyInjection.DataProtectionServices/<GetDefaultServices>d__0.MoveNext () <0x0021b>
  at Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd (Microsoft.Framework.DependencyInjection.IServiceCollection,System.Collections.Generic.IEnumerable`1<Microsoft.Framework.DependencyInjection.ServiceDescriptor>) <0x00064>
  at Microsoft.Framework.DependencyInjection.DataProtectionServiceCollectionExtensions.AddDataProtection (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0002b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.ConfigureDefaultServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0001b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.AddMvc (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x00013>
  at OmniSharp.Startup.ConfigureServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0003f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
```

**Comment by reapazor** [comment] 2015-09-02 19:30
This looks like something todo with VSCode installation more so then a plugin, and having looked at your attempts at UniVSCode as well I suspect there might be other issues at play.

> Can't find custom attr constructor image: /Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/approot/packages/Microsoft.AspNet.Cryptography.Internal/1.0.0-beta4/lib/dnx451/Microsoft.AspNet.Cryptography.Internal.dll mtoken: 0x0a000004
> Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met

Seems to be the core of the issue, and unrelated to the plugin.

**Comment by vexir** [comment] 2015-09-02 19:41
A VSCode rep I'm talking to suggested it might be an out of date version of Mono, but I just updated to the latest and it doesn't seem to help.

Any idea what might be the problem with my VSCode install?

**Comment by reapazor** [comment] 2015-09-02 19:46
I just looked at my VSCode install ...

The error message ... 
> Can't find custom attr constructor image: /Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/approot/packages/Microsoft.AspNet.Cryptography.Internal/1.0.0-beta4/lib/dnx451/Microsoft.AspNet.Cryptography.Internal.dll mtoken: 0x0a000004

Mentions a path `/Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/approot/packages/...` 

My install doesnt have that, I suspect yours is similar ...

`/Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/packages/...` 

Would be the valid pathing (that nasty "approot" is killing you) to what its looking for, so I suspect something is fubar in a config somewhere?

**Comment by vexir** [comment] 2015-09-02 19:50
Doesn't look like it. I was able to cd all the way down into where that Microsoft.AspNet.Cryptography.Internal.dll file is and it exists. Something it's doing perhaps is causing the error? I'm not sure how to debug any further...

**Comment by reapazor** [comment] 2015-09-02 19:53
A quick googling gives me some ideas ... 

http://stackoverflow.com/questions/8873091/mono-compiling-error-could-not-load-type-system-runtime-compilerservices-refe

Kind of suggests that the compiler you've got installed may be older then the latest, which would back what the Visual Studio Code rep was saying.

Did you install mono from source at any point in the past?

**Comment by vexir** [comment] 2015-09-02 19:55
It's entirely possible, though I don't really remember it. I did do a 

```
brew reinstall mono
```
which I'd imagine would have fixed it  - my mono version now reads 4.2

**Comment by vexir** [comment] 2015-09-02 19:58
Perhaps does Unity use a version of Mono that's installed somewhere else that isn't being updated by my terminal command?

**Comment by reapazor** [comment] 2015-09-02 20:01
Unity itself has its own mono runtime, but we're not using that for any of this (nor is VS Code).

What I would personally do in this situation is uninstall from homebrew mono (hoping that it cleanly does it) and then download either mono directly from the source:

http://www.mono-project.com/download/

Or you can also grab Xamarin Studio, and have it install Mono for you (its made by the makers of Mono):
http://xamarin.com/platform

**Comment by vexir** [comment] 2015-09-02 20:11
Hey! That did the trick. I guess home-brew was installing some crazy version of mono. 

I'm getting code completion and go to declaration and all that fun stuff now.

Debugging doesn't seem to work however. Stuck a breakpoint in an update loop on one of my mono behaviors and it never got hit. The console log did say: 
```[VSCode] Debug Port Found (56876)```

Doesn't seem to have actually worked? Anything else I need to do?

**Comment by reapazor** [comment] 2015-09-02 20:12
Did you go to the debug tab in VSCode and hit the play button there?

**Comment by vexir** [comment] 2015-09-02 20:14
Yes, but it doesn't look like the plugin is writing to Launch.json, which still looks like this:

```
			"name": "Attach",
			"type": "node",
			// TCP/IP address. Default is "localhost".
			"address": "localhost",
			// Port to attach to.
			"port": 5858,
			"sourceMaps": false
```

Is that something I have to do manually?

**Comment by reapazor** [comment] 2015-09-02 20:17
That is strange ...  what version of Visual Studio Code are you using?

In Visual Studio Code 0.8.0, they moved the configuration directory, and the latest pull of my plugin has that, there is a previous release on the repo (https://github.com/dotBunny/VSCode/releases/tag/1.6.5) marked for Visual Studio Code < 0.7.2. It isn't as awesome as the latest version :) but it should work if that's the case.

**Comment by vexir** [comment] 2015-09-02 20:25
Just updated to 0.8.0 and it works now. Might be a good thing to mention in the readme?

Thanks for all the help!

**Comment by reapazor** [comment] 2015-09-02 20:26
No problem :) had me worried for a little bit. 

I'll put a note in the README right now.

**Comment by vexir** [comment] 2015-09-02 20:55
Looks like this process broke code completion in MonoDevelop. Is there a way to have both MonoDevelop and VSCode live alongside each other in peace and harmony?

**Comment by reapazor** [comment] 2015-09-02 20:58
I believe so, I have to experiment with it a bit ...

Unity 5.2, I believe is where the feature shows up, that allows you to force the type of project / solution files that are saved out, and that would remove the need for me to scrub them. 

This would then allow for the project file to be left in a state that MonoDevelop/Xamarin could use them

One option is to simply disable the integration from the menu, the generated project file should then work with MD.

**Comment by vexir** [comment] 2015-09-02 21:16
Integration is not checked. Still getting no code completion/highlighting and strange "text editor error"s in MD.

```
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.CSharp.Completion.CSharpCompletionTextEditorExtension.GetParameterCompletionCommandOffset (System.Int32& cpos) [0x00000] in /home/builduser/buildslave/monodevelop/build/monodevelop/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs:524
```

**Comment by reapazor** [comment] 2015-09-02 21:24
Hmm ... is that Unity's included MonoDevelop?

**Comment by vexir** [comment] 2015-09-02 21:24
Yup!

**Comment by reapazor** [comment] 2015-09-02 21:30
You just can't win :(

I double checked and MD, included with Unity does have its own version of the mono.framework, and to make matters worse, that chunk of code looks to be commented out in the latest versions of [MD](https://github.com/mono/monodevelop/blob/master/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs).

Just use VS Code? :)

**Comment by vexir** [comment] 2015-09-02 21:43
Haha, I'm doing so now. I'm running into some auto complete problems however - some Unity system functions aren't completed, and go to file (command+P) seems to have to do a search every time I ask it to go somewhere. For instance, it wasn't able to autocomplete Debug.Log just now.

**Comment by vexir** [comment] 2015-09-02 21:55
Erm, I also seem to have lost my go to declaration and all that, though I'm not getting any OmniSharp errors.

**Comment by reapazor** [comment] 2015-09-03 02:16
Its a bug I just found I'm committing a fix momentarily.

**Comment by vexir** [comment] 2015-09-03 03:43
Just grabbed latest (8:43 PST), doesn't seem to have fixed it. Where'd my code complete go :( VSCode doesn't even recognize the Time class and such things *cry*

**Comment by reapazor** [comment] 2015-09-03 03:49
Not sure, I just checked and its still working for me ..did you play with the workspace exclusions by chance? 

May need to write out new  ones (which contain the solution and project files)

**Comment by vexir** [comment] 2015-09-03 03:51
My workspace settings:

```
{
    "files.exclude": {
        "**/.DS_Store": true,
        "**/.git": true,
        "**/*.booproj": true,
        "**/*.csproj": true,
        "**/*.pidb": true,
        "**/*.sln": true,
        "**/*.suo": true,
        "**/*.user": true,
        "**/*.userprefs": true,
        "**/*.unityproj": true,
        "**/*.dll": true,
        "**/*.exe": true,
        "**/*.gif": true,
        "**/*.ico": true,
        "**/*.jpg": true,
        "**/*.jpeg": true,
        "**/*.mid": true,
        "**/*.midi": true,
        "**/*.pdf": true,
        "**/*.png": true,
        "**/*.psd": true,
        "**/*.tga": true,
        "**/*.tif": true,
        "**/*.tiff": true,
        "**/*.wav": true,
        "**/*.asset": true,
        "**/*.cubemap": true,
        "**/*.flare": true,
        "**/*.mat": true,
        "**/*.meta": true,
        "**/*.*.meta": true,
        "**/*.pidb.meta": true,
        "**/*.prefab": true,
        "**/*.unity": true,
        "**/*.3ds": true,
        "**/*.3DS": true,
        "**/*.fbx": true,
        "**/*.FBX": true,
        "**/*.lxo": true,
        "**/*.LXO": true,
        "**/*.ma": true,
        "**/*.MA": true,
        "**/*.obj": true,
        "**/*.OBJ": true,
        "build/": true,
        "Build/": true,
        "library/": true,
        "Library/": true,
        "obj/": true,
        "Obj/": true,
        "ProjectSettings/": true,
        "temp/": true,
        "Temp/": true
    }
}
```

**Comment by reapazor** [comment] 2015-09-03 03:53
Yup, as I suspected.

https://github.com/dotBunny/VSCode/commit/a69432231c40fa2fdc7816c73919ae82e0e4f2df

Got rid of an issue where hidding solution and project files caused Visual Studio Code not to work right.

If you write out your workspace settings again it should fix that (with the latest)

**Comment by vexir** [comment] 2015-09-03 03:59
That did it! Thanks!

VSCode did tell me that some things did not finish loading properly and when I clicked show Output, it tossed me to the OmniSharp log, the top part of which is this:

```
[INFO] Starting OmniSharp at '/Users/mathe015/Repositories/myProject/myProject-csharp.sln'...
[INFO] Started OmniSharp from '/Applications/Visual Studio Code.app/Contents/Resources/app/plugins/vs.language.csharp.o/bin/omnisharp' with process id 54691...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/mathe015/Repositories/myProject' on host 54667.
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations /Users/mathe015/.dnx/runtimes/dnx-mono.default
/Users/mathe015/.dnx/runtimes/kre-mono.default
/Users/mathe015/.dnx/packages/KRE-Mono.default
/Users/mathe015/.k/runtimes/dnx-mono.default
/Users/mathe015/.k/runtimes/kre-mono.default
/Users/mathe015/.k/packages/KRE-Mono.default
/Users/mathe015/.kre/runtimes/dnx-mono.default
/Users/mathe015/.kre/runtimes/kre-mono.default
/Users/mathe015/.kre/packages/KRE-Mono.default.
Visit https://github.com/aspnet/Home for an installation guide.
```

Anything I should be concerned about?

**Comment by reapazor** [comment] 2015-09-03 04:05
I've seen that Dnx path error pop up before, i dont believe its harmful ... but it is interesting that you are seeing it still. 

It might be related to Visual Studio Codes bundled apps (https://github.com/OmniSharp/omnisharp-roslyn/issues/249) ... not exactly sure.

**Comment by vexir** [comment] 2015-09-03 04:30
Gotcha. Good to know.

Debugging is working afaik, but it looks like hovering over a value doesn't do anything? The docs say you can inspect that way. Would that be a VSCode issue or could this integration be the cause?

**Comment by reapazor** [comment] 2015-09-03 12:48
You know I was worried for a moment ...

You need to make sure to set the external editor to the Visual Studio Code app for it to work it seems, I'll see about adding something that does that for you :)

**Comment by reapazor** [comment] 2015-09-03 12:50
<img width="396" alt="screenshot 2015-09-03 08 50 10" src="https://cloud.githubusercontent.com/assets/99292/9658628/cf154778-5218-11e5-90be-cc87ff0fa0fd.png">

**Comment by reapazor** [comment] 2015-09-03 13:31
Automatic support for this should be coming today, just have to finish up saving/restoring old when you disable the integration.

**Comment by vexir** [comment] 2015-09-03 18:54
Just pulled latest - doesn't look like my External Script Editor changed. Changing it manually to VSCode also didn't fix the hover inspection problem (local variables still work). 

I've also been getting a lot of Unity lock ups when debugging. I don't have specific repro steps yet, but will work on getting you some. It's usually when I try and hit resume in VSCode.

**Comment by reapazor** [comment] 2015-09-03 21:40
I definately am going to need some reproduction steps on the External Editor Script test --- but it might be possible that you didn't turn off the integration and then turn it back on (its during the enable/disable process that it rights those changes).

But this does bring a good point up, if enabled I should enforce those settings always. *noted*

As for the lockups, ive seen them too ... i mean i know you cant go back to Unity till you resume/etc from VSCode. I suspect this might be a Visual Studio Code issue.

Your right hovering over I havent seen for debuggin, the local variables still work ... are you adding watches?

**Comment by reapazor** [comment] 2015-09-03 22:10
<img width="1342" alt="screenshot 2015-09-03 18 08 59" src="https://cloud.githubusercontent.com/assets/99292/9672252/f8410404-5266-11e5-9ddd-ab9235b17dad.png">

It is odd ... but i think its Visual Studio Code's end

**Comment by vexir** [comment] 2015-09-03 23:32
Yeah, there are other oddities. I just hit a breakpoint that I had turned off a while ago, and then when I tried to hit resume in VSCode, nothing happened. I hit stop in VSCode, and it released and went "blue", but Unity stayed stuck and now I have to restart it ;(

**Comment by vexir** [comment] 2015-09-03 23:33
I think this debugging hang up piece is the last thing that I need to really jump on board with VSCode as my main code editor for Unity. Any ideas?

**Comment by reapazor** [comment] 2015-09-03 23:34
I'm going to pass this little problem up the Visual Studio Code chain :)

It is almost like they are not sending the "stop debugging" command back to Unity.

**Comment by vexir** [comment] 2015-09-03 23:47
Awesome. Keep me updated!

**Comment by reapazor** [comment] 2015-09-04 13:00
https://vimeo.com/dotbunny/vscode

I was shooting this and even captured the hang in there :(

**Comment by vexir** [comment] 2015-09-08 18:38
@reapazor had my coworker install the plugin from scratch - his external code editor changed automatically and everything, but it doesn't look like omnisharp finds his project automatically i.e. it says pick a project and his autocomplete doesn't work at all.

**Comment by vexir** [comment] 2015-09-08 19:01
@reapazor I'm also not able to look into the contents of a List when I debug - it displays this error instead:

```This request is not supported by the protocol version implemented by the debuggee.```

**Comment by reapazor** [comment] 2015-09-08 19:27
@vexir Is there any spaces in the project path ? 

As for the list, that would be something for the Visual Studio Code team.

**Comment by vexir** [comment] 2015-09-08 19:40
No spaces. The code completion is working for me, just not for my coworker. Not sure what's different about our installations. 

Eshan

**Comment by reapazor** [comment] 2015-09-08 19:44
Whats your path to your project, unity and vscode ....
whats his?

**Comment by reapazor** [comment] 2015-09-08 19:45
I've seen random occasions where VSCode didnt work, but then a force sync fixed it.

**Comment by vexir** [comment] 2015-09-08 21:06
Mine:
```
~/Applications/Visual Studio Code.app
~/Applications/Unity/Unity.app
```

His:
```
~/Applications/Visual Studio Code.app
~/Applications/Unity/Unity.app
```

**Comment by reapazor** [comment] 2015-09-08 23:05
Any thing fancy (special characters?) in your user names?

**Comment by vexir** [comment] 2015-09-08 23:07
Nope. Letters and numbers, no spaces.

**Comment by vexir** [comment] 2015-09-09 19:45
By the way, it's a guaranteed Unity crash if you hit the Stop button in VSCode.

**Comment by vexir** [comment] 2015-09-09 20:02
Ah, and apparently breakpoints aren't removed properly. So you can get into a situation where you can't remove a breakpoint and you can't detach the debugger i.e. you hit the breakpoint every time no matter what until you restart Unity.

**Comment by tnaseem** [comment] 2015-09-10 23:30
I'm having similar problem to @vexir too... In that, I've set up everything as per the posting on the Visual Studio Code site, but I get no intellisense, and the flame icon is stuck fading in and out continuously (no projects listed).

The OmniSharp log file only has one line it:

`[INFO] Starting OmniSharp at '/Users/tarique/Cloud/OneDrive/Development/Miltary Sim/Source/MilitarySim/MilitarySim.sln'...`

I've done a 'Force Sync Project' and removed any spaces in the folder names, but still not working.

Not sure whether this is in vscode, or something with the plugin, so mentioning here to see if anyone can shed some light on it!

Note: The solution was created from scratch by selecting 'Open Project' (as I've never used monodevelop, favouring ST3).

**Comment by vexir** [comment] 2015-09-11 00:27
Strange... I wonder why it works for me but not for anyone else? Can't think of what I've done differently...

**Comment by reapazor** [comment] 2015-09-11 01:12
I've seen VSCode randomly not have intellisense, I've had to close it down and restart/populate project for it to work.

@tnaseem  can you email me your .sln file as well as your .proj files ? (reapazor 'at' gmail 'dot' com) I wonder if the scrubber is missing something for you.

Though I would assume an error would occur with OmniSharp.


One bug that I've filled with the VSCode folks is that a large project often doesnt load into VSCode properly.

**Comment by tnaseem** [comment] 2015-09-11 02:07
Thanks! Just emailed...

**Comment by jagwire** [comment] 2015-09-15 16:34
I'm seeing the same issue as tnaseem. Has there been any progress on this?

**Comment by reapazor** [comment] 2015-09-15 16:55
Turns out he was on an older version of Unity.

Also for the debugging issue, word from the VSCode team is that it will be resolved in their next update.

**Closed** 2015-09-15 16:55 UTC
Labels: bug
